/* eslint-disable @typescript-eslint/no-unused-vars */
/**
 * READ-ONLY LLM CONTEXT - Do not edit this file.
 *
 * These MCP/Gateway types are now part of agentcore/agentcore.json (merged from former mcp.json).
 * Purpose: MCP gateways, tool definitions, and compute configurations
 */

// ─────────────────────────────────────────────────────────────────────────────
// ROOT SCHEMA: AgentCoreMcpSpec
// ─────────────────────────────────────────────────────────────────────────────

interface AgentCoreMcpSpec {
  agentCoreGateways: AgentCoreGateway[];
  mcpRuntimeTools?: AgentCoreMcpRuntimeTool[];
}

// ─────────────────────────────────────────────────────────────────────────────
// GATEWAY
// ─────────────────────────────────────────────────────────────────────────────

interface AgentCoreGateway {
  name: string; // @regex ^([0-9a-zA-Z][-]?){1,100}$ @max 100
  description?: string;
  targets: AgentCoreGatewayTarget[];
  /** Enable semantic search for tool discovery. @default true */
  enableSemanticSearch?: boolean; // default true
  /** Exception verbosity level. @default 'NONE' */
  exceptionLevel?: 'NONE' | 'DEBUG'; // default 'NONE'
}

interface AgentCoreGatewayTarget {
  name: string;
  targetType: GatewayTargetType;
  toolDefinitions?: ToolDefinition[];
  compute?: ToolComputeConfig;
  endpoint?: string; // URL - required for external MCP Server targets
  outboundAuth?: OutboundAuth;
  apiGateway?: ApiGatewayConfig;
  /** Schema source for openApiSchema / smithyModel targets. */
  schemaSource?: { inline: { path: string } } | { s3: { uri: string; bucketOwnerAccountId?: string } };
  lambdaFunctionArn?: LambdaFunctionArnConfig;
}

interface OutboundAuth {
  type: 'OAUTH' | 'API_KEY' | 'NONE';
  credentialName?: string;
  scopes?: string[];
}

interface ApiGatewayConfig {
  restApiId: string;
  stage: string;
  apiGatewayToolConfiguration: {
    toolFilters: { filterPath: string; methods: ApiGatewayHttpMethod[] }[];
    toolOverrides?: { name: string; path: string; method: ApiGatewayHttpMethod; description?: string }[];
  };
}

type ApiGatewayHttpMethod = 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH' | 'HEAD' | 'OPTIONS';

interface LambdaFunctionArnConfig {
  lambdaArn: string;
  toolSchemaFile: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// MCP RUNTIME TOOL
// ─────────────────────────────────────────────────────────────────────────────

/**
 * AgentCore MCP Runtime tool servers.
 * Directly addressable by agents via generated DNS endpoint.
 *
 * Use the `bindings` array to grant agents permission to invoke this tool.
 * Each binding grants InvokeAgentRuntime permission and sets an environment
 * variable with the runtime ARN on the bound agent.
 */
interface AgentCoreMcpRuntimeTool {
  name: string; // @min 1
  toolDefinition: ToolDefinition;
  compute: AgentCoreRuntimeComputeConfig;
  bindings?: McpRuntimeBinding[]; // Agents that can invoke this tool
}

/**
 * Binding from an MCP runtime tool to an agent.
 * When present, the agent is granted InvokeAgentRuntime permission
 * and receives the runtime ARN in the specified environment variable.
 */
interface McpRuntimeBinding {
  agentName: string; // @min 1 - name of the agent from spec.agents array
  envVarName: string; // @regex ^[A-Za-z_][A-Za-z0-9_]*$ @max 255 - env var for runtime ARN
}

// ─────────────────────────────────────────────────────────────────────────────
// TOOL DEFINITION
// ─────────────────────────────────────────────────────────────────────────────

interface ToolDefinition {
  name: string; // @regex ^([0-9a-zA-Z][-]?){1,100}$ @max 100
  description: string; // @min 1
  inputSchema: SchemaDefinition;
  outputSchema?: SchemaDefinition;
}

interface SchemaDefinition {
  type: SchemaPrimitiveType;
  description?: string;
  items?: SchemaDefinition; // For array type
  properties?: Record<string, SchemaDefinition>; // For object type
  required?: string[]; // Required property names
}

type SchemaPrimitiveType = 'string' | 'number' | 'object' | 'array' | 'boolean' | 'integer';

// ─────────────────────────────────────────────────────────────────────────────
// COMPUTE CONFIGURATION (discriminated union on 'host')
// ─────────────────────────────────────────────────────────────────────────────

type ToolComputeConfig = LambdaComputeConfig | AgentCoreRuntimeComputeConfig;

interface LambdaComputeConfig {
  host: 'Lambda';
  implementation: ToolImplementationBinding;
  nodeVersion?: NodeRuntime; // Required if language === 'TypeScript'
  pythonVersion?: PythonRuntime; // Required if language === 'Python'
  timeout?: number; // @min 1 @max 900 seconds
  memorySize?: number; // @min 128 @max 10240 MB
  iamPolicy?: IamPolicyDocument;
}

interface AgentCoreRuntimeComputeConfig {
  host: 'AgentCoreRuntime';
  implementation: ToolImplementationBinding; // Must be language === 'Python'
  runtime?: RuntimeConfig;
  iamPolicy?: IamPolicyDocument;
}

// ─────────────────────────────────────────────────────────────────────────────
// TOOL IMPLEMENTATION BINDING
// ─────────────────────────────────────────────────────────────────────────────

interface ToolImplementationBinding {
  language: 'TypeScript' | 'Python';
  path: string; // @min 1 - relative path to source file
  handler: string; // @min 1 - function name
}

// ─────────────────────────────────────────────────────────────────────────────
// RUNTIME CONFIGURATION
// ─────────────────────────────────────────────────────────────────────────────

interface RuntimeConfig {
  artifact: 'CodeZip';
  name: string; // @regex ^[a-zA-Z][a-zA-Z0-9_]{0,47}$ @max 48
  pythonVersion: PythonRuntime;
  entrypoint: string; // @regex ^[a-zA-Z0-9_][a-zA-Z0-9_/.-]*\.py(:[a-zA-Z_][a-zA-Z0-9_]*)?$
  codeLocation: string; // Directory path
  networkMode?: NetworkMode; // default 'PUBLIC'
  description?: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// IAM POLICY
// ─────────────────────────────────────────────────────────────────────────────

interface IamPolicyDocument {
  Version: string;
  Statement: unknown[];
  [key: string]: unknown; // Additional IAM fields allowed
}

// ─────────────────────────────────────────────────────────────────────────────
// ENUMS
// ─────────────────────────────────────────────────────────────────────────────

type GatewayTargetType = 'lambda' | 'mcpServer' | 'openApiSchema' | 'smithyModel' | 'apiGateway' | 'lambdaFunctionArn';
type PythonRuntime = 'PYTHON_3_10' | 'PYTHON_3_11' | 'PYTHON_3_12' | 'PYTHON_3_13';
type NodeRuntime = 'NODE_18' | 'NODE_20' | 'NODE_22';
type NetworkMode = 'PUBLIC' | 'VPC';
